config/routes.rb
Rails.application.routes.draw do
  resources :ideas
  resources :users
  resources :first_names

  root to: 'ideas#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/first_name.rb
class FirstName < ApplicationRecord
end

app/models/idea.rb
class Idea < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/first_names_controller.rb
class FirstNamesController < ApplicationController
  before_action :set_first_name, only: [:show, :edit, :update, :destroy]

  # GET /first_names
  # GET /first_names.json
  def index
    @first_names = FirstName.all
  end

  # GET /first_names/1
  # GET /first_names/1.json
  def show
  end

  # GET /first_names/new
  def new
    @first_name = FirstName.new
  end

  # GET /first_names/1/edit
  def edit
  end

  # POST /first_names
  # POST /first_names.json
  def create
    @first_name = FirstName.new(first_name_params)

    respond_to do |format|
      if @first_name.save
        format.html { redirect_to @first_name, notice: 'First name was successfully created.' }
        format.json { render :show, status: :created, location: @first_name }
      else
        format.html { render :new }
        format.json { render json: @first_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /first_names/1
  # PATCH/PUT /first_names/1.json
  def update
    respond_to do |format|
      if @first_name.update(first_name_params)
        format.html { redirect_to @first_name, notice: 'First name was successfully updated.' }
        format.json { render :show, status: :ok, location: @first_name }
      else
        format.html { render :edit }
        format.json { render json: @first_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /first_names/1
  # DELETE /first_names/1.json
  def destroy
    @first_name.destroy
    respond_to do |format|
      format.html { redirect_to first_names_url, notice: 'First name was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_first_name
      @first_name = FirstName.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def first_name_params
      params.require(:first_name).permit(:last_name, :maiden_name, :formatted_name, :phonetic_first_name, :phonetic_last_name, :formatted_phonetic_name, :headline, :location, :industry, :current_share, :num_connections, :num_connections_capped, :sumary, :specialties, :positions, :picture_url, :picture_url_original, :site_standard_profile_request, :api_standard_profile_request, :public_profile_url, :email_address)
    end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:name, :description, :image, :stage, :looking_for, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :maiden_name, :formatted_name, :phonetic_first_name, :phonetic_last_name, :formatted_phonetic_name, :headline, :location, :industry, :current_share, :num_connections, :num_connections_capped, :sumary, :specialties, :positions, :picture_url, :picture_url_original, :site_standard_profile_request, :api_standard_profile_request, :public_profile_url, :email_address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/first_names_helper.rb
module FirstNamesHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/first_names/_form.html.erb
<%= form_with(model: first_name, local: true) do |form| %>
  <% if first_name.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(first_name.errors.count, "error") %> prohibited this first_name from being saved:</h2>

      <ul>
      <% first_name.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :first_name_last_name %>
  </div>

  <div class="field">
    <%= form.label :maiden_name %>
    <%= form.text_field :maiden_name, id: :first_name_maiden_name %>
  </div>

  <div class="field">
    <%= form.label :formatted_name %>
    <%= form.text_field :formatted_name, id: :first_name_formatted_name %>
  </div>

  <div class="field">
    <%= form.label :phonetic_first_name %>
    <%= form.text_field :phonetic_first_name, id: :first_name_phonetic_first_name %>
  </div>

  <div class="field">
    <%= form.label :phonetic_last_name %>
    <%= form.text_field :phonetic_last_name, id: :first_name_phonetic_last_name %>
  </div>

  <div class="field">
    <%= form.label :formatted_phonetic_name %>
    <%= form.text_field :formatted_phonetic_name, id: :first_name_formatted_phonetic_name %>
  </div>

  <div class="field">
    <%= form.label :headline %>
    <%= form.text_field :headline, id: :first_name_headline %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :first_name_location %>
  </div>

  <div class="field">
    <%= form.label :industry %>
    <%= form.number_field :industry, id: :first_name_industry %>
  </div>

  <div class="field">
    <%= form.label :current_share %>
    <%= form.text_field :current_share, id: :first_name_current_share %>
  </div>

  <div class="field">
    <%= form.label :num_connections %>
    <%= form.number_field :num_connections, id: :first_name_num_connections %>
  </div>

  <div class="field">
    <%= form.label :num_connections_capped %>
    <%= form.check_box :num_connections_capped, id: :first_name_num_connections_capped %>
  </div>

  <div class="field">
    <%= form.label :sumary %>
    <%= form.text_area :sumary, id: :first_name_sumary %>
  </div>

  <div class="field">
    <%= form.label :specialties %>
    <%= form.text_field :specialties, id: :first_name_specialties %>
  </div>

  <div class="field">
    <%= form.label :positions %>
    <%= form.text_field :positions, id: :first_name_positions %>
  </div>

  <div class="field">
    <%= form.label :picture_url %>
    <%= form.text_field :picture_url, id: :first_name_picture_url %>
  </div>

  <div class="field">
    <%= form.label :picture_url_original %>
    <%= form.text_field :picture_url_original, id: :first_name_picture_url_original %>
  </div>

  <div class="field">
    <%= form.label :site_standard_profile_request %>
    <%= form.text_field :site_standard_profile_request, id: :first_name_site_standard_profile_request %>
  </div>

  <div class="field">
    <%= form.label :api_standard_profile_request %>
    <%= form.text_field :api_standard_profile_request, id: :first_name_api_standard_profile_request %>
  </div>

  <div class="field">
    <%= form.label :public_profile_url %>
    <%= form.text_field :public_profile_url, id: :first_name_public_profile_url %>
  </div>

  <div class="field">
    <%= form.label :email_address %>
    <%= form.text_field :email_address, id: :first_name_email_address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/first_names/edit.html.erb
<h1>Editing First Name</h1>

<%= render 'form', first_name: @first_name %>

<%= link_to 'Show', @first_name %> |
<%= link_to 'Back', first_names_path %>

app/views/first_names/index.html.erb
<p id="notice"><%= notice %></p>

<h1>First Names</h1>

<table>
  <thead>
    <tr>
      <th>Last name</th>
      <th>Maiden name</th>
      <th>Formatted name</th>
      <th>Phonetic first name</th>
      <th>Phonetic last name</th>
      <th>Formatted phonetic name</th>
      <th>Headline</th>
      <th>Location</th>
      <th>Industry</th>
      <th>Current share</th>
      <th>Num connections</th>
      <th>Num connections capped</th>
      <th>Sumary</th>
      <th>Specialties</th>
      <th>Positions</th>
      <th>Picture url</th>
      <th>Picture url original</th>
      <th>Site standard profile request</th>
      <th>Api standard profile request</th>
      <th>Public profile url</th>
      <th>Email address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @first_names.each do |first_name| %>
      <tr>
        <td><%= first_name.last_name %></td>
        <td><%= first_name.maiden_name %></td>
        <td><%= first_name.formatted_name %></td>
        <td><%= first_name.phonetic_first_name %></td>
        <td><%= first_name.phonetic_last_name %></td>
        <td><%= first_name.formatted_phonetic_name %></td>
        <td><%= first_name.headline %></td>
        <td><%= first_name.location %></td>
        <td><%= first_name.industry %></td>
        <td><%= first_name.current_share %></td>
        <td><%= first_name.num_connections %></td>
        <td><%= first_name.num_connections_capped %></td>
        <td><%= first_name.sumary %></td>
        <td><%= first_name.specialties %></td>
        <td><%= first_name.positions %></td>
        <td><%= first_name.picture_url %></td>
        <td><%= first_name.picture_url_original %></td>
        <td><%= first_name.site_standard_profile_request %></td>
        <td><%= first_name.api_standard_profile_request %></td>
        <td><%= first_name.public_profile_url %></td>
        <td><%= first_name.email_address %></td>
        <td><%= link_to 'Show', first_name %></td>
        <td><%= link_to 'Edit', edit_first_name_path(first_name) %></td>
        <td><%= link_to 'Destroy', first_name, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New First Name', new_first_name_path %>

app/views/first_names/new.html.erb
<h1>New First Name</h1>

<%= render 'form', first_name: @first_name %>

<%= link_to 'Back', first_names_path %>

app/views/first_names/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Last name:</strong>
  <%= @first_name.last_name %>
</p>

<p>
  <strong>Maiden name:</strong>
  <%= @first_name.maiden_name %>
</p>

<p>
  <strong>Formatted name:</strong>
  <%= @first_name.formatted_name %>
</p>

<p>
  <strong>Phonetic first name:</strong>
  <%= @first_name.phonetic_first_name %>
</p>

<p>
  <strong>Phonetic last name:</strong>
  <%= @first_name.phonetic_last_name %>
</p>

<p>
  <strong>Formatted phonetic name:</strong>
  <%= @first_name.formatted_phonetic_name %>
</p>

<p>
  <strong>Headline:</strong>
  <%= @first_name.headline %>
</p>

<p>
  <strong>Location:</strong>
  <%= @first_name.location %>
</p>

<p>
  <strong>Industry:</strong>
  <%= @first_name.industry %>
</p>

<p>
  <strong>Current share:</strong>
  <%= @first_name.current_share %>
</p>

<p>
  <strong>Num connections:</strong>
  <%= @first_name.num_connections %>
</p>

<p>
  <strong>Num connections capped:</strong>
  <%= @first_name.num_connections_capped %>
</p>

<p>
  <strong>Sumary:</strong>
  <%= @first_name.sumary %>
</p>

<p>
  <strong>Specialties:</strong>
  <%= @first_name.specialties %>
</p>

<p>
  <strong>Positions:</strong>
  <%= @first_name.positions %>
</p>

<p>
  <strong>Picture url:</strong>
  <%= @first_name.picture_url %>
</p>

<p>
  <strong>Picture url original:</strong>
  <%= @first_name.picture_url_original %>
</p>

<p>
  <strong>Site standard profile request:</strong>
  <%= @first_name.site_standard_profile_request %>
</p>

<p>
  <strong>Api standard profile request:</strong>
  <%= @first_name.api_standard_profile_request %>
</p>

<p>
  <strong>Public profile url:</strong>
  <%= @first_name.public_profile_url %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @first_name.email_address %>
</p>

<%= link_to 'Edit', edit_first_name_path(@first_name) %> |
<%= link_to 'Back', first_names_path %>

app/views/ideas/_form.html.erb
<%= form_with(model: idea, local: true) do |form| %>
  <% if idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :idea_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :idea_description %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image, id: :idea_image %>
  </div>

  <div class="field">
    <%= form.label :stage %>
    <%= form.text_field :stage, id: :idea_stage %>
  </div>

  <div class="field">
    <%= form.label :looking_for %>
    <%= form.text_field :looking_for, id: :idea_looking_for %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :idea_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render 'form', idea: @idea %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ideas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image</th>
      <th>Stage</th>
      <th>Looking for</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.name %></td>
        <td><%= idea.description %></td>
        <td><%= idea.image %></td>
        <td><%= idea.stage %></td>
        <td><%= idea.looking_for %></td>
        <td><%= idea.user.last_name %></td>
        <td><%= link_to 'Show', idea %></td>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Idea', new_idea_path, class: "waves-effect waves-light btn" %>

app/views/ideas/new.html.erb
<h1>New Idea</h1>

<%= render 'form', idea: @idea %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @idea.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @idea.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @idea.image %>
</p>

<p>
  <strong>Stage:</strong>
  <%= @idea.stage %>
</p>

<p>
  <strong>Looking for:</strong>
  <%= @idea.looking_for %>
</p>

<p>
  <strong>User:</strong>
  <%= @idea.user %>
</p>

<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Baseemprendating</title>
    <%= csrf_meta_tags %>


    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js"></script>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :user_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :user_last_name %>
  </div>

  <div class="field">
    <%= form.label :maiden_name %>
    <%= form.text_field :maiden_name, id: :user_maiden_name %>
  </div>

  <div class="field">
    <%= form.label :formatted_name %>
    <%= form.text_field :formatted_name, id: :user_formatted_name %>
  </div>

  <div class="field">
    <%= form.label :phonetic_first_name %>
    <%= form.text_field :phonetic_first_name, id: :user_phonetic_first_name %>
  </div>

  <div class="field">
    <%= form.label :phonetic_last_name %>
    <%= form.text_field :phonetic_last_name, id: :user_phonetic_last_name %>
  </div>

  <div class="field">
    <%= form.label :formatted_phonetic_name %>
    <%= form.text_field :formatted_phonetic_name, id: :user_formatted_phonetic_name %>
  </div>

  <div class="field">
    <%= form.label :headline %>
    <%= form.text_field :headline, id: :user_headline %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :user_location %>
  </div>

  <div class="field">
    <%= form.label :industry %>
    <%= form.number_field :industry, id: :user_industry %>
  </div>

  <div class="field">
    <%= form.label :current_share %>
    <%= form.text_field :current_share, id: :user_current_share %>
  </div>

  <div class="field">
    <%= form.label :num_connections %>
    <%= form.number_field :num_connections, id: :user_num_connections %>
  </div>

  <div class="field">
    <%= form.label :num_connections_capped %>
    <%= form.check_box :num_connections_capped, id: :user_num_connections_capped %>
  </div>

  <div class="field">
    <%= form.label :sumary %>
    <%= form.text_area :sumary, id: :user_sumary %>
  </div>

  <div class="field">
    <%= form.label :specialties %>
    <%= form.text_field :specialties, id: :user_specialties %>
  </div>

  <div class="field">
    <%= form.label :positions %>
    <%= form.text_field :positions, id: :user_positions %>
  </div>

  <div class="field">
    <%= form.label :picture_url %>
    <%= form.text_field :picture_url, id: :user_picture_url %>
  </div>

  <div class="field">
    <%= form.label :picture_url_original %>
    <%= form.text_field :picture_url_original, id: :user_picture_url_original %>
  </div>

  <div class="field">
    <%= form.label :site_standard_profile_request %>
    <%= form.text_field :site_standard_profile_request, id: :user_site_standard_profile_request %>
  </div>

  <div class="field">
    <%= form.label :api_standard_profile_request %>
    <%= form.text_field :api_standard_profile_request, id: :user_api_standard_profile_request %>
  </div>

  <div class="field">
    <%= form.label :public_profile_url %>
    <%= form.text_field :public_profile_url, id: :user_public_profile_url %>
  </div>

  <div class="field">
    <%= form.label :email_address %>
    <%= form.text_field :email_address, id: :user_email_address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Maiden name</th>
      <th>Formatted name</th>
      <th>Phonetic first name</th>
      <th>Phonetic last name</th>
      <th>Formatted phonetic name</th>
      <th>Headline</th>
      <th>Location</th>
      <th>Industry</th>
      <th>Current share</th>
      <th>Num connections</th>
      <th>Num connections capped</th>
      <th>Sumary</th>
      <th>Specialties</th>
      <th>Positions</th>
      <th>Picture url</th>
      <th>Picture url original</th>
      <th>Site standard profile request</th>
      <th>Api standard profile request</th>
      <th>Public profile url</th>
      <th>Email address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.maiden_name %></td>
        <td><%= user.formatted_name %></td>
        <td><%= user.phonetic_first_name %></td>
        <td><%= user.phonetic_last_name %></td>
        <td><%= user.formatted_phonetic_name %></td>
        <td><%= user.headline %></td>
        <td><%= user.location %></td>
        <td><%= user.industry %></td>
        <td><%= user.current_share %></td>
        <td><%= user.num_connections %></td>
        <td><%= user.num_connections_capped %></td>
        <td><%= user.sumary %></td>
        <td><%= user.specialties %></td>
        <td><%= user.positions %></td>
        <td><%= user.picture_url %></td>
        <td><%= user.picture_url_original %></td>
        <td><%= user.site_standard_profile_request %></td>
        <td><%= user.api_standard_profile_request %></td>
        <td><%= user.public_profile_url %></td>
        <td><%= user.email_address %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Maiden name:</strong>
  <%= @user.maiden_name %>
</p>

<p>
  <strong>Formatted name:</strong>
  <%= @user.formatted_name %>
</p>

<p>
  <strong>Phonetic first name:</strong>
  <%= @user.phonetic_first_name %>
</p>

<p>
  <strong>Phonetic last name:</strong>
  <%= @user.phonetic_last_name %>
</p>

<p>
  <strong>Formatted phonetic name:</strong>
  <%= @user.formatted_phonetic_name %>
</p>

<p>
  <strong>Headline:</strong>
  <%= @user.headline %>
</p>

<p>
  <strong>Location:</strong>
  <%= @user.location %>
</p>

<p>
  <strong>Industry:</strong>
  <%= @user.industry %>
</p>

<p>
  <strong>Current share:</strong>
  <%= @user.current_share %>
</p>

<p>
  <strong>Num connections:</strong>
  <%= @user.num_connections %>
</p>

<p>
  <strong>Num connections capped:</strong>
  <%= @user.num_connections_capped %>
</p>

<p>
  <strong>Sumary:</strong>
  <%= @user.sumary %>
</p>

<p>
  <strong>Specialties:</strong>
  <%= @user.specialties %>
</p>

<p>
  <strong>Positions:</strong>
  <%= @user.positions %>
</p>

<p>
  <strong>Picture url:</strong>
  <%= @user.picture_url %>
</p>

<p>
  <strong>Picture url original:</strong>
  <%= @user.picture_url_original %>
</p>

<p>
  <strong>Site standard profile request:</strong>
  <%= @user.site_standard_profile_request %>
</p>

<p>
  <strong>Api standard profile request:</strong>
  <%= @user.api_standard_profile_request %>
</p>

<p>
  <strong>Public profile url:</strong>
  <%= @user.public_profile_url %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @user.email_address %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>